### ISSUE TITLE
Question: What is the module system used?

### ISSUE THREAD

**Issue by nickforddev** [STRd6/2A03#14]
Cool project!

Looking at the demo, and the source (also I've never used coffeescript), there doesn't seem to be any trace of your build process, or what the JSON module system is. Is there a name for this system of building your JS to JSON?

**Comment by STRd6** [comment]
Here's the editor I use to build the project: https://danielx.net/editor/

The module system is https://github.com/distri/require/blob/master/main.coffee.md

The basic idea is that the editor loads projects from GitHub repos and publishes them to GitHub Pages to make static apps. All the dependencies are pulled at build time. The published package includes the source as well as the built code so that a package can be loaded back in the editor even outside of GitHub.

Thank you for your interest and I'm happy to answer any further questions!

**Comment by nickforddev** [comment]
That's really interesting, thanks for the info!
